apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: node-prom-29524
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-prom-29524 
  name: node-prom-29524
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: node-prom-29524 
